
kind: RoleBinding 
apiVersion: rbac.authorization.k8s.io/v1beta1 
metadata: 
 name: kiali-service-account-role-binding
subjects: 
- kind: ServiceAccount 
  name: kiali-service-account  
  namespace: istio-system
roleRef: 
  kind: Role 
  name: kiali-service-account-role
  apiGroup: rbac.authorization.k8s.io
